# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc57b497984dd39d5f4a7f5fe64f2abd13f65d52f9a0f64211bfbab83b576ab884f2a269e7f5592c190cbf44732711f564ba25ae501fdf010915a8537b189dda

test:
  secret_key_base: 0d3595db0b6fbe852ddb4205302bcb88591d8bef916737883c0438c83bc8d541ceccb252117229cf3e8b80d9bcac8dfc9b0bc91bee048fcc2f2079ab0974f289

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
